### ISSUE TITLE
index out of range

### ISSUE THREAD

**Issue by andyleap** [turnage/graw#19]
Just tried to set up mention monitoring and such, and I've started getting:

```
panic: runtime error: index out of range

goroutine 39 [running]:
panic(0x8407e0, 0xc42000c100)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/turnage/graw/streams/internal/monitor.(*monitor).fixTip(0xc4203d9c80, 0x0, 0x0)
        /home/vendan/go/src/github.com/turnage/graw/streams/internal/monitor/monitor.go:128 +0x4ed
github.com/turnage/graw/streams/internal/monitor.(*monitor).Update(0xc4203d9c80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/vendan/go/src/github.com/turnage/graw/streams/internal/monitor/monitor.go:80 +0x33e
github.com/turnage/graw/streams.flow(0xaa7280, 0xc4203d9c80, 0xc420134120, 0xc420134180, 0xc420294720, 0xc420294780, 0xc4202947e0)
        /home/vendan/go/src/github.com/turnage/graw/streams/streams.go:230 +0x7c
created by github.com/turnage/graw/streams.stream
        /home/vendan/go/src/github.com/turnage/graw/streams/streams.go:207 +0xe9
```

whenever I mention my bot

**Comment by turnage** [comment]
Thank you for opening an issue!

I didn't catch this because my test accounts already had mentions in their inbox, and this appears to happen with listings that have no elements. I tested with an empty subreddit; feel free to re-open if you still experience a problem.
