### ISSUE TITLE
Weird "unexpected fault address" error 

### ISSUE THREAD

**Issue by guliyevemil1** [turnage/graw#34]
Hey, I'm not sure if this is at all my fault, but I got this stack trace today. I can't figure out what happened wrong and was wondering if you had seen anything like it before or knew something that I didn't. Thanks!

```unexpected fault address 0x0
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0x4a82e8]

goroutine 212813943 [running]:
runtime.throw(0xb9e8b4, 0x5)
	/usr/local/go/src/runtime/panic.go:605 +0x95 fp=0xc422f0e970 sp=0xc422f0e950 pc=0x42bc15
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:374 +0x227 fp=0xc422f0e9c0 sp=0xc422f0e970 pc=0x4424c7
reflect.StructTag.Lookup(0x646465722e777777, 0x6d6f632e7469, 0xba451f, 0xc, 0xc422f0ee90, 0xfc0e50, 0xc4201b5030)
	/usr/local/go/src/reflect/type.go:1165 +0x38 fp=0xc422f0ea20 sp=0xc422f0e9c0 pc=0x4a82e8
reflect.StructTag.Get(0x646465722e777777, 0x6d6f632e7469, 0xba451f, 0xc, 0x0, 0xa6b9c0)
	/usr/local/go/src/reflect/type.go:1148 +0x49 fp=0xc422f0ea68 sp=0xc422f0ea20 pc=0x4a8289
vendor/github.com/mitchellh/mapstructure.(*Decoder).decodeStruct(0xc421a01370, 0x0, 0x0, 0xaac580, 0xc425d207b0, 0xb92040, 0xc4236cec00, 0x199, 0xc422f0f4e8, 0x4109d2)
	/go/src/vendor/github.com/mitchellh/mapstructure/mapstructure.go:706 +0xe26 fp=0xc422f0f400 sp=0xc422f0ea68 pc=0x6ec176
vendor/github.com/mitchellh/mapstructure.(*Decoder).decode(0xc421a01370, 0x0, 0x0, 0xaac580, 0xc425d207b0, 0xb92040, 0xc4236cec00, 0x199, 0x1, 0xc42956a380)
	/go/src/vendor/github.com/mitchellh/mapstructure/mapstructure.go:225 +0x6c3 fp=0xc422f0f518 sp=0xc422f0f400 pc=0x6e64d3
vendor/github.com/mitchellh/mapstructure.(*Decoder).Decode(0xc421a01370, 0xaac580, 0xc425d207b0, 0x0, 0x1)
	/go/src/vendor/github.com/mitchellh/mapstructure/mapstructure.go:180 +0xb3 fp=0xc422f0f578 sp=0xc422f0f518 pc=0x6e5de3
vendor/github.com/mitchellh/mapstructure.Decode(0xaac580, 0xc425d207b0, 0xa51900, 0xc4236cec00, 0x0, 0x0)
	/go/src/vendor/github.com/mitchellh/mapstructure/mapstructure.go:122 +0xa4 fp=0xc422f0f5b8 sp=0xc422f0f578 pc=0x6e59b4
vendor/github.com/turnage/graw/reddit.parsePost(0xc422f0f728, 0xc425d207b0, 0xba3d68, 0xb)
	/go/src/vendor/github.com/turnage/graw/reddit/parse.go:183 +0x6a fp=0xc422f0f600 sp=0xc422f0f5b8 pc=0x6f125a
vendor/github.com/turnage/graw/reddit.parseListing(0xc422a6eea0, 0x1a1e2, 0x1fe00, 0xa51b00, 0xc422a6eea0, 0x0, 0x0, 0x0, 0x0, 0xc423979810, ...)
	/go/src/vendor/github.com/turnage/graw/reddit/parse.go:147 +0x559 fp=0xc422f0f750 sp=0xc422f0f600 pc=0x6f0b39
vendor/github.com/turnage/graw/reddit.parseRawListing(0xc4230c8000, 0x1a1e2, 0x1fe00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/vendor/github.com/turnage/graw/reddit/parse.go:79 +0x11b fp=0xc422f0f7c8 sp=0xc422f0f750 pc=0x6f027b
vendor/github.com/turnage/graw/reddit.(*parserImpl).parse(0xfea8d8, 0xc4230c8000, 0x1a1e2, 0x1fe00, 0x1fe00, 0x0, 0x0, 0x411200, 0x120, 0xb1fda0, ...)
	/go/src/vendor/github.com/turnage/graw/reddit/parse.go:54 +0x5a fp=0xc422f0f888 sp=0xc422f0f7c8 pc=0x6efe1a
vendor/github.com/turnage/graw/reddit.(*reaperImpl).reap(0xc420b32780, 0xc4227f4b00, 0xa, 0xc4272b6a20, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/vendor/github.com/turnage/graw/reddit/reaper.go:76 +0x239 fp=0xc422f0f978 sp=0xc422f0f888 pc=0x6f16e9
vendor/github.com/turnage/graw/reddit.(*scanner).Listing(0xc4203a0400, 0xc4227f4b00, 0xa, 0xc423962de0, 0x9, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/vendor/github.com/turnage/graw/reddit/scanner.go:42 +0x1f1 fp=0xc422f0fa98 sp=0xc422f0f978 pc=0x6f21b1
vendor/github.com/turnage/graw/reddit.(*bot).Listing(0xc420b35140, 0xc4227f4b00, 0xa, 0xc423962de0, 0x9, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	<autogenerated>:1 +0xde fp=0xc422f0fbb8 sp=0xc422f0fa98 pc=0x6f312e
vendor/github.com/turnage/graw/streams/internal/monitor.(*monitor).harvest(0xc429fe9c80, 0xc423962de0, 0x9, 0x14, 0xc424068000, 0x14, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/vendor/github.com/turnage/graw/streams/internal/monitor/monitor.go:96 +0xc9 fp=0xc422f0fce8 sp=0xc422f0fbb8 pc=0x9c9bc9
vendor/github.com/turnage/graw/streams/internal/monitor.(*monitor).Update(0xc429fe9c80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/vendor/github.com/turnage/graw/streams/internal/monitor/monitor.go:87 +0xd2 fp=0xc422f0fe58 sp=0xc422f0fce8 pc=0x9c97c2
vendor/github.com/turnage/graw/streams.flow(0xf6ea20, 0xc429fe9c80, 0xc422708cc0, 0xc422708d20, 0xc4236d57a0, 0xc4236d5800, 0xc4236d5860)
	/go/src/vendor/github.com/turnage/graw/streams/streams.go:253 +0x1c7 fp=0xc422f0ffa8 sp=0xc422f0fe58 pc=0x9cb2b7
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc422f0ffb0 sp=0xc422f0ffa8 pc=0x45c131
created by vendor/github.com/turnage/graw/streams.stream
	/go/src/vendor/github.com/turnage/graw/streams/streams.go:230 +0xe9
```

**Comment by turnage** [comment]
I won't have time to look into this in detail soon, but it appears that Reddit's response doesn't match the expectations I set up for [mapstructure](https://github.com/mitchellh/mapstructure).

That happens [here](https://github.com/turnage/graw/blob/f28dd708bed84317008cf0a609552b981bc6a6f4/reddit/parse.go#L183). If I were to debug this myself I'd log the responses there and inspect one that causes the failure. I had some trouble catching various oddities in the Reddit responses, such as fields being boolean sometimes and integers other times. It's likely I missed one of those things.

**Comment by Flexicon** [comment]
Should probably be closed since no further information was given and it's been 2 years 😄
